### ISSUE TITLE
Is FLASH loader extremely slow?

### ISSUE THREAD

**Issue by steinnymir** [OpenCOMPES/sed#100]
While trying to load express data from flash, comparing it to the old online data format, I encountered a series of problematic bugs. At first, the datasets obtained (same beamtime, simultaneously written in both formats) were containing different number of counts. Express seems to have more total counts, but somehow less counts in the focus region after binning. While I still don't understand the origin of this, I tested this with SED:
Loading a dataset, parallel or not was EXTREMELY slow. For a single run, made of 25 files (350mb each) it takes  2-3 minutes to load, even after the parquets were generated. The long time seems to be in the fill_na and explosion step, I think. Is this normal? or does my maxwell have something weird going on?

Also, binning on the dataframe genrated this way is also much slower than it was with hextof-express. I though the loader should be the same... 
@zainsohail04 any thoughts?

**Comment by zainsohail04** [comment]
Honestly, I am also a bit confused with the slow readout. According to others, they said the speed is fine so maybe it's a maxwell problem. I only restructured the code a bit and it shouldn't have made it slower. Perhaps the joblib library has a lot of overhead..
 
But anyways, the fill_na method has a line where it has to compute the values from dask array which takes forever. I have been trying to find a solution that doesn't require it but couldn't figure. But it is indeed odd how it's slower compared to hextof-processor. If you have any ideas, please let me know.

One thing I would suggest trying out is to use FlashLoader without the overhead of SED and see how much it improves speed. Otherwise I can also try to do it.

**Comment by steinnymir** [comment]
I will look more into this, I also find it really odd. I'll try see if I can isolate what makes it so slow. But I am happy we did not get any complaint in this direction from the current beamtime.

**Comment by zainsohail04** [comment]
Okay so I just spoke to Yves about this.

On the local workspace, reading and filling nans is happening very fast, how it used to.

Problem is the cluster is slow. I really am confused why that is

I did do some restructuring to the fill_na method where instead of storing the dataframes as an attribute, they're just directly passed to fill_na, which concatenates it when returning.

So this change could be the culprit, though I really fail to understand why.

**Comment by steinnymir** [comment]
good to hear the local machine works well!

It would be strange if storing as an attribute has such a performance impact, but who knows!
Are they using a version before these changes on the local machine?

**Comment by zainsohail04** [comment]
The latest one, on the contrary. Its tagged v0.1. 
All very odd.

**Comment by zainsohail04** [comment]
Going to try pasha with the flash loader and see if it leads to improvement.

If you don't mind @daviddoji , could you provide a link to your code for reading h5 using pasha?

**Comment by rettigl** [comment]
I know this is a bit off-topic, but I would like to understand your concern that loading the sed package takes a lot of time. This is what I get when loading the current "flash" branch in a jupyter notebook:
![grafik](https://user-images.githubusercontent.com/53396064/218854718-e59adce2-e16f-4784-8249-4455051796dc.png)

(installed with -e in a virtual environment)

**Comment by rettigl** [comment]
I cannot benchmark the flash loader itself due to the lack of example data.

**Comment by steinnymir** [comment]
I have tested this again, and get loading times between 3 and 8 seconds too (local machine).  I guess there were other problems causing this...

**Comment by steinnymir** [comment]
solved in #165
