### ISSUE TITLE
inconsistency trainId assignment

### ISSUE THREAD

**Issue by daviddoji** [OpenCOMPES/sed#348]
Looking at the `sxp_workflow` tutorial, once the runs for the energy calibration are loaded, if one looks at how the trainIds are assigned, you get the following plot:
![image](https://github.com/OpenCOMPES/sed/assets/4411314/42f2c9a5-2c35-4698-9247-003ddb345331)

As the runs for the energy calibration are loaded in the following order:
![image](https://github.com/OpenCOMPES/sed/assets/4411314/175e0e9d-bd63-4efe-8076-a49b7dc236a7)

I could expect something like this:
![image](https://github.com/OpenCOMPES/sed/assets/4411314/96f0732c-4a76-4039-b98c-306c6866aa2d)

due to how the runs have been read.

This issue will lead to further problems if you need to correlate your data afterwards with PP laser, for example

**Comment by rettigl** [comment]
The "issue" comes from the fact, that the index is reset for every dataframe partition (file). In order to get a continous index, use, e.g. `plt.plot(sp.dataframe.trainId.compute().values, ".")`
![grafik](https://github.com/OpenCOMPES/sed/assets/53396064/ae2301b4-ee16-4967-b8bf-6a1fabb4ad53)
i.e. don't plot against index, which is automatically done for dataframe objects.
Regarding your expectation, you will always only see one run at a time, because they are loaded sequentially. See the for loop in the code.

**Comment by rettigl** [comment]
Closing, because it works as expected.
