### ISSUE TITLE
Change to src layout

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#506]
Most large python projects have adopted a layout, where the source code files reside inside a src folder. This avoids potential problems with packaging and testing, see e.g. here: https://hynek.me/articles/testing-packaging/

I suggest doing the same for sed for V1

**Comment by zain-sohail** [comment]
I also ported to the src layout in hextof-processor but I see no real advantage of it, especially considering we only have one top level package called sed in the repo. 
And from my experience, since it's less standard, always confuses people wanting to do an editable install.
https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/

Also many large projects from my knowledge don't use it, and others do
https://github.com/pandas-dev/pandas
https://github.com/numpy/numpy
https://github.com/dask/dask

**Comment by rettigl** [comment]
> I also ported to the src layout in hextof-processor but I see no real advantage of it, especially considering we only have one top level package called sed in the repo.
> And from my experience, since it's less standard, always confuses people wanting to do an editable install.

The big advantage is that you don't do a silent, unintended import of the package, and that you development version behavior deviates from the packaged version. I find that relevant for good development practice. I also sorted things a litte bit more systematically in the PR #508 to strictly separate source code from everything else.
The editable install works just the same way as before. Only thing is that you might have to re-install when the layout changes. But as we are introducing this on the v1, this should not be an issue.

**Comment by rettigl** [comment]
Closed by #508
