### ISSUE TITLE
Rename SedProcessor

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#91]
Let's discuss this. A possible alternative would be Processor

**Comment by zainsohail04** [comment]
We were discussing this today. And think a good name would be PESWorkflow or something similar. Since the processor.py module currently is a workflow manager for PES experiments, and is not general enough for all single event dataframes. 

So the suggestion is to have core contain only core necessities for SED and PESWorkflow as a derivative of it.

We already have another user interested in adoption this code for their case. I think a discussion will happen sometime mid feb (Dima will write to us).

**Comment by steinnymir** [comment]
duplicate of #184

**Comment by rettigl** [comment]
obsolete
