### ISSUE TITLE
Binning with Tuple produces unexpected behavior

### ISSUE THREAD

**Issue by zainsohail04** [OpenCOMPES/sed#95]
**Describe the bug**
The documentation states using a tuple with 3 parameters should be the start, stop and step_size. But currently, it is assuming it to be the num_steps.

**To Reproduce**
```
axes = ['dldPosX', 'dldPosY']
bins = [(430,900,1), (430,900,1)]
res = sp.compute(bins=bins, axes=axes)
```

**Expected behavior**
The behavior should be tuple(start, stop, step_size). Test currently tests tuple(start, stop, num_steps).

**Comment by steinnymir** [comment]
User experience at HEXTOF pushed us to set the preferred triplet to be start, stop, step_size, so this is what I would stick with.
I see however the fast binning method is designed with number_of_steps, so if someone has strong arguments for it, I'm ok with this too.

An alternative option would be to reduce the options for input and ask each as explicit argument, e.g. `bin_dataframe(start=0,stop=100,step=1)` and `bin_dataframe(start=0,stop=100,number_of_steps=101)` should give equivalent outputs.

**Comment by rettigl** [comment]
I suppose that we make this consistent for the actual binning functions, and implement different behavior in the class wrapper functions. I find giving the number of points to be more natural, as you have better overview over the amount of data you create...

**Comment by zainsohail04** [comment]
Using the number of steps in backend makes good sense, then. We just have to have the wrappers designed in such a way that it's clear to the user what they are doing (like Steinn suggested).

I did a fix of the bug in branch 'flash' for now. Since users are already using it, I'll make a PR with that specific change.

**Comment by rettigl** [comment]
We should discuss again what is the most natural thing to expect from the binning function to do.
I would opt for simulating a behavior that you would also have with a program that scans an axis:
if you tell it to start at A, end at B and do N steps, the natural expected behavior would be that the stepsize is (A-B)/N, and that the scan has indeed N+1points, to include the endpoints:

Example: 0, 10, 10 => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

This is at least how all scanning programs I know work like.

If we want to reproduce this with the binning, I would also expect these points to be the center coordinates of each bin. This results in N+2 bin edges, with the same stepsize and shifted by half a bin:

Example: 0, 10, 10 => [-.5, .5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5]

Still, I would return the bin centers as coordinates for the xarray, as this is the default was coordinates work in xarrays, as far as I know. Also this allows without complication to plot the data after reducing to 1 dimension.

If you agree to this, the question is still how should we interprete, if a list of bins is given: Should this be interpreted as bin edges or as bin centers? I would opt for the second one, but this is inconsistent then with the default behavior of np.histogramdd. In any case, I would return the bin centers again, and I would find it somewhat strange, if the returned coordinates are different from the given ones. 

One caviat is that there is not only one way to define the bin edges based on (non-uniform) bin centers. A natural choice is taking the midpoint between centers, but there could e.g. also be logarithmically spaced bins, etc. I think, however, that this is a very edge case we maybe don't have to consider (the question is also then if the bin centers are a meaningful representation).

What's your opinion?

**Comment by rettigl** [comment]
I implemented something similar to my suggestion in PR #98. The only difference is, that I did not include the extension of bins by one. Let's discuss what is the most expected behavior.

**Comment by steinnymir** [comment]
### generation of the bins
these are the options I se:
Start is typically included. 
Stop can be included but not always, as I would give the third parameter priority. The third can be one of three cases: 
- *step size*: as in np.arange, stop not included (does not spill over the range) i.e. `(0.,3.5,1.)` gives `np.array(0.,1.,2.,3.)`
- *number of steps*: as in your example mimicking scanning setups. stop included i.e. `(0,3,3)` gives `np.array(0.,1.,2.,3.)`
- *number of points*: as in np.linspace, stop included, i.e. `(0,3,4)` gives `np.array(0.,1.,2.,3.)`)

For the first case, one could add the option `endpoint=True` to force include the last point even if it spills over.

My feeling is the last option is the clearest, as you are requesting the "shape" of the output. But I have nothing against any of the three options. We should however be clear with labeling them as step, step-size and number-of-points.

### Labeling of each bin
You are right that its important to lable bins with their center point. In this regard, I would have our binning method return the edges (as it optionally does) as np.histogramdd does. The binning function which returns an xarray should instead have coordinates shifted to the center point for uniform axes (as you suggest).

The default behavior for bins in xarray is handled with the pandas `Interval` object: 
```python
import numpy as np
import xarray as xr

c = np.arange(0,10000,10)
v = np.random.rand(len(c))
xarr = xr.DataArray(v, dims='x', coords={'x':c})

logscale = np.logspace(0,10,11,base=2)
grouped = xarr.groupby_bins('x', bins=logscale).mean()
grouped.coords['x_bins'].values[1]
>>> Interval(10.0, 100.0, closed='right')
```
If we plot this, even though the scale is logarithmic, it places the data point in the center of the bin. We could keep this behaviour, and stay consistent with xarray. Alternatively, would be nice to implement the use of the Interval object, but it becomes annoying to work with then.

**Comment by rettigl** [comment]
Closed for now, but new issue to discuss which future options to add #123
